### ISSUE TITLE
cargo install error

### ISSUE THREAD

**Issue by cymqqqq** [vleue/bevmnist#16]
When I run cargo install wasm-bindgen-cli https, error comes:
error: failed to run custom build command for `curl-sys v0.4.39+curl-7.74.0`

Caused by:
  could not execute process `C:\Users\cym\AppData\Local\Temp\cargo-installcRTlqM\release\build\curl-sys-832fd609f2fd14f1\build-script-build` (never executed)

Caused by:
  拒绝访问。 (os error 5)
warning: build failed, waiting for other jobs to finish...
error: failed to compile `wasm-bindgen-cli v0.2.69`, intermediate artifacts can be found at `C:\Users\cym\AppData\Local\Temp\cargo-installcRTlqM`

Caused by:
  build failed
     Ignored package `https v1.10.0` is already installed, use --force to override
     Summary Successfully installed https! Failed to install wasm-bindgen-cli (see error(s) above).
How can I fix it?

**Comment by mockersf** [comment]
this seems an issue with `wasm-bindgen-cli`... this is handled here : https://github.com/rustwasm/wasm-bindgen/tree/master/crates/cli

"拒绝访问" means "access denied" according to google translate, so maybe a permission error?

**Comment by cymqqqq** [comment]
THX for answering：）
I have fixed this problem.
